### ISSUE TITLE
dataset download question

### ISSUE THREAD

**Issue by suojifeng** [ellaampy/GEE-to-NPY#1]
May I ask if this dataset is now available for download? I'm having some problems with it.

**Comment by ellaampy** [comment]
This repo is a data download workflow that allows you to pull time series sentinel-1/2 from Google Earth Engine. It requires a geojson of farm boundaries as input

**Comment by suojifeng** [comment]
May I ask the form of this polygons, lab_rpg？
i found the code
label_names = ['CODE_GROUP']
    lab_rpg = dict([(l, {}) for l in label_names])  

just like this  {  label_name1: {(ID_PARCEL : Label value)}, label_name2: {(ID_PARCEL : Label value)}

The form I think is this {'CODE_GROUP': {'2852037': '3', '12133340': '3', '2911346': '25', '9980966': '25', '14614284': '18', '14614828': '3', '14614829': '3', '14623475': '25', '14623476': '25', '14623477': '25', '14623479': '18', '14670247': '28'}}

If I give you the data { "type": "Feature", "properties": { "ID_PARCEL": "2852037", "SURF_PARC": 3.19, "CODE_CULTU": "ORH", "CODE_GROUP": "3", "CULTURE_D1": "DVN", "CULTURE_D2": "DPH" }} ，I would like to know this lab_rpg form of this data

I ran your code is this result in lab_rpg format {'C': {}, 'O': {}, 'D': {}, 'E': {}, '_': {}, 'G': {}, 'R': {}, 'U': {}, 'P': {}}I know it's wrong.
I appreciate that you're going to answer my questions.

**Comment by ellaampy** [comment]
Given your example, 
"
_If I give you the data { "type": "Feature", "properties": { "ID_PARCEL": "2852037", "SURF_PARC": 3.19, "CODE_CULTU": "ORH", "CODE_GROUP": "3", "CULTURE_D1": "DVN", "CULTURE_D2": "DPH" }} ，I would like to know this lab_rpg form of this data_
"

the lab_rpg form should be  {'CODE_GROUP': {'2852037': '3'}}. 

Please note that the input is a featurecollection (in geojson format). The repo already contains an [example](https://github.com/ellaampy/GEE-to-NPY/tree/master/sample_geojson)

**Comment by suojifeng** [comment]
Simply use the following runtime program
python get_data.py E:\\mutilmodal\\download\\sample_farm.geojson E:\\mutilmodal\\download\\s1_data --label_names CODE_GROUP --id_field ID_PARCEL --col_id COPERNICUS/S1_GRD --footprint_id '[154]' --start_date 2021-01-01 --end_date 2021-01-31 --speckle_filter mean
It's the code you gave me that hasn't changed.  the results is
 total ignored parcels 12
 processing time -> 0:00:22.343825
The intermediate result  lab_rbg is {'CODE_GROUP': {'2852037': '3', '12133340': '3', '2911346': '25', '9980966': '25', '14614284': '18', '14614828': '3', '14614829': '3', '14623475': '25', '14623476': '25', '14623477': '25', '14623479': '18', '14670247': '28'}}
The intermediate result  polygons is {'2852037': [[[-4.09070567753393, 48.60287783267349], [-4.090591849392066, 48.60288155936102], [-4.090438419939259, 48.60343587528367], [-4.089446453861799, 48.60321945360145], [-4.088771202609729, 48.60308248805168], [-4.088787050828358, 48.603005713086866], [-4.08885037159158, 48.60284617479801], [-4.088957839992809, 48.602704493295874], [-4.089186474518206, 48.602487949304894], [-4.089604409268681, 48.60208384221675], [-4.089863004179392, 48.601757905568356], [-4.089927240538067, 48.60174177796526], [-4.090393414838022, 48.60194347822294], [-4.090951102641328, 48.602170455155196], [-4.091596484454547, 48.60245162901326], [-4.09209507056953, 48.60292601965336], [-4.092314486771893, 48.602937506992546], [-4.092476398990425, 48.604016104552656], [-4.091863754547975, 48.60382828023001], [-4.09097564656884, 48.603546230808576], [-4.091079979393706, 48.60324487580802], [-4.091172499081786, 48.602913491640166], [-4.09070567753393, 48.60287783267349]]], '12133340': [[[-4.085628997088684, 48.60074284685146], [-4.08609507
7069849, 48.60059316040346], [-4.085965318746096, 48.60022096592386], [-4.085861976264233, 48.5998466438925], [-4.085735560284657, 48.599625735619256], [-4.085705341430904, 48.599579337737666], [-4.08601863
2176295, 48.59949851262142], [-4.086326817797974, 48.59944044553321], [-4.086473090566682, 48.59961365032113], [-4.086554146594612, 48.59976713360411], [-4.086633556960781, 48.599979812055025], [-4.08669169
0355554, 48.60015987405662], [-4.086734064423355, 48.60041792109803], [-4.086747309058269, 48.60063917366419], [-4.08719301130685, 48.600606187078995], [-4.0873848572643, 48.6008053232569], [-4.087642438875
605, 48.60132282674708], [-4.087750579145717, 48.6015887898998], [-4.088235849470462, 48.60290955908958], [-4.087733636006681, 48.60283929629536], [-4.087181135576003, 48.6027291612072], [-4.086149926242819
, 48.60251112715187], [-4.085773832803834, 48.60242125545908], [-4.085425674168253, 48.60227359388467], [-4.085301425428559, 48.6022057124048], [-4.085165437119449, 48.602106297860985], [-4.085071663621742,
 48.602025859215836], [-4.084983417256652, 48.60193316008193], [-4.084867987726502, 48.60177277507645], [-4.084749373151569, 48.60156240095411], [-4.084692379934911, 48.60143436604702], [-4.084650644403808,
 48.60131260077911], [-4.084632245917721, 48.60123006677442], [-4.084750658804628, 48.601159287597575], [-4.084859873764406, 48.60107549358731], [-4.085200264006952, 48.600867359941084], [-4.085628997088684
, 48.60074284685146]]], '2911346': [[[-4.088108019900371, 48.604338846658486], [-4.088556848112176, 48.60372418868446], [-4.089111994784052, 48.60400334339666], [-4.08906787172367, 48.604313231379564], [-4.
088974922763563, 48.604690267317196], [-4.088889371538728, 48.60498430144619], [-4.088883790973807, 48.60502494682419], [-4.088873281327248, 48.60533402343728], [-4.088724853300868, 48.60534082960971], [-4.
088525819725694, 48.60532229123431], [-4.088348607492584, 48.60529595084829], [-4.088158160611356, 48.60526820104477], [-4.087875217609617, 48.605235124343835], [-4.087608245798359, 48.60522281449217], [-4.
087595893144119, 48.6051126746192], [-4.087642653748202, 48.60495489464393], [-4.087816675184825, 48.60469250097545], [-4.088108019900371, 48.604338846658486]]], '9980966': [[[-4.08985572928029, 48.60696294
688372], [-4.089838318264079, 48.606754942759274], [-4.089804899974069, 48.60663397378798], [-4.089888015823368, 48.60657469573767], [-4.089813061834467, 48.60635271440053], [-4.089799468301218, 48.60630946
118454], [-4.089797696601033, 48.60628497411516], [-4.089778784410713, 48.606043236445636], [-4.08968312620329, 48.60556630275939], [-4.089902091220138, 48.605619836781116], [-4.090084565305498, 48.60565505
669236], [-4.090176933879814, 48.605652612196145], [-4.090256797110251, 48.60563760183557], [-4.090367426092509, 48.6056330372651], [-4.09053796319851, 48.60563720534314], [-4.090572247237525, 48.6054117629
8996], [-4.090630144167078, 48.605246397310744], [-4.090719659046269, 48.60508632359269], [-4.090754878156814, 48.60500429130948], [-4.090834294999102, 48.60500877012596], [-4.091254915278102, 48.6051250678
38735], [-4.091392089942161, 48.60517299247708], [-4.09124667889989, 48.60546268939654], [-4.091187037201207, 48.605683495927295], [-4.091191639284894, 48.605785693021545], [-4.091232859237321, 48.606020968
818356], [-4.091298403818739, 48.606082641705235], [-4.091448479891206, 48.60606137837134], [-4.091594369310116, 48.60605471600015], [-4.091653160181488, 48.606688126734625], [-4.091651436675953, 48.6066920
5271562], [-4.091649153597311, 48.60676468977583], [-4.09155934939844, 48.606752606649884], [-4.091211605473481, 48.60672930838697], [-4.09106779292301, 48.60673994646697], [-4.090905309755451, 48.606760920
467444], [-4.090813024257351, 48.60679819507877], [-4.090578060036203, 48.606945440400615], [-4.090178908784027, 48.607237753622634], [-4.090002507444068, 48.60734972800099], [-4.089866305715226, 48.6074050
0447818], [-4.089819509764422, 48.60717416199956], [-4.089822676530521, 48.60709506452668], [-4.08985572928029, 48.60696294688372]]], '14614284': [[[-4.090109589777399, 48.60080862907085], [-4.0900136905616
19, 48.600739548], [-4.090028132209327, 48.60066387532432], [-4.089767450648738, 48.60059882872706], [-4.089716524659943, 48.60058612132775], [-4.089706692230725, 48.60058366786985], [-4.089444123369203, 48
.60066390352399], [-4.089305801342256, 48.6006465498908], [-4.089245169563337, 48.60066656235215], [-4.089167611608375, 48.60074395136488], [-4.089071304999307, 48.60077429349322], [-4.088919630003504, 48.6
0074953599396], [-4.08891294549978, 48.60074583476005], [-4.088705225519909, 48.6006383424326], [-4.088662260967618, 48.60036730909983], [-4.089316949020966, 48.600330269908184], [-4.089314245405981, 48.600
31576316881], [-4.089940871012753, 48.60028276230958], [-4.090997647643675, 48.6001120607854], [-4.092253770010641, 48.60005547704296], [-4.092962907971318, 48.59999328392047], [-4.092974773983832, 48.60013
12825753], [-4.093403270878095, 48.60015794051203], [-4.093632148655399, 48.600500875983556], [-4.092893934197098, 48.60049169243057], [-4.092776967085483, 48.60044949369443], [-4.092700091102483, 48.600429
4929929], [-4.092575804892307, 48.60043588778337], [-4.092366809559683, 48.600455544979376], [-4.092223962961049, 48.60049584902815], [-4.092180002201719, 48.60054766097859], [-4.092094720545833, 48.6005681
2588115], [-4.091971009408134, 48.60056731548449], [-4.091804435101443, 48.60053524996454], [-4.091755685622937, 48.60052893955887], [-4.091613210567586, 48.60059483603173], [-4.091228689199038, 48.60060755
191185], [-4.090971092210213, 48.600610644398174], [-4.090880945975362, 48.60061806920786], [-4.0907711480567, 48.60073119904837], [-4.090737817288704, 48.600758812147724], [-4.090702142949318, 48.600769142
37533], [-4.09054768166355, 48.60073532302972], [-4.090434991875381, 48.60072463069784], [-4.09032422469043, 48.60073944602696], [-4.090167512955825, 48.60082566194199], [-4.090146210326058, 48.600816684093
3], [-4.090109589777399, 48.60080862907085]]], '14614828': [[[-4.089511446882807, 48.60413455980302], [-4.089368214580714, 48.603797974756596], [-4.089426148336481, 48.60372043821832], [-4.08950902236966, 4
8.603455023146935], [-4.089573780690785, 48.603385250753924], [-4.089687452197975, 48.60337995123288], [-4.090118627087474, 48.60347034267763], [-4.091035529583768, 48.603679970510264], [-4.091590779586712,
 48.60385483434725], [-4.092182683429006, 48.60403774833088], [-4.092009924919421, 48.60435856294138], [-4.091883840487144, 48.604579238299536], [-4.091708790672101, 48.60483767251937], [-4.091593911915826,
 48.605004391927004], [-4.091502270289966, 48.605194316334334], [-4.091254647532221, 48.60511176229024], [-4.090839047393208, 48.60499823552737], [-4.090741659976182, 48.60499790958257], [-4.090538626974251
, 48.60501617492584], [-4.090285623327338, 48.60500771897381], [-4.089969285440115, 48.60495384928841], [-4.09001228709351, 48.604781172665206], [-4.090140857642004, 48.60447633092389], [-4.090192207284724,
 48.604308276534546], [-4.090086786492978, 48.60427153594827], [-4.090000975387911, 48.60426538833795], [-4.089828257650406, 48.60423368634034], [-4.0897405006673, 48.60421330361143], [-4.089554030813107, 4
8.60414860824616], [-4.089511446882807, 48.60413455980302]]], '14614829': [[[-4.088558278336071, 48.60363113991667], [-4.088469165281418, 48.6035893151401], [-4.088281702252832, 48.60354004893319], [-4.0878
88698875629, 48.60342209320148], [-4.087401949780097, 48.60328514803457], [-4.087331619159652, 48.60326782382207], [-4.086775039556605, 48.60315143648389], [-4.086435426519111, 48.60310816852872], [-4.08632
4028880449, 48.603072802139046], [-4.086253051586334, 48.60301658105638], [-4.086196133541369, 48.6028703708122], [-4.08612340541, 48.60266463806202], [-4.086275110416733, 48.602678127114565], [-4.087105535
27319, 48.6028314578916], [-4.088288871359014, 48.60308053906217], [-4.089079706040541, 48.60327072152218], [-4.089068186395064, 48.60341921497332], [-4.089100256138443, 48.60373511662026], [-4.088913828981
894, 48.60368889635286], [-4.088558278336071, 48.60363113991667]]], '14623475': [[[-4.093138933976361, 48.60127944051979], [-4.092264848736396, 48.60161692321913], [-4.092260955417791, 48.601614615681385], 
[-4.09085453615629, 48.60211780090077], [-4.09042335802473, 48.60193903306139], [-4.090265689158021, 48.6018774962914], [-4.089935056903751, 48.60171778220912], [-4.089867641668174, 48.60161737662419], [-4.
089861043215282, 48.60158171753095], [-4.090097164385379, 48.60144366986414], [-4.09041025086997, 48.60126580154644], [-4.090540671456801, 48.60121491456126], [-4.090781612965577, 48.60113776455108], [-4.09
0935082935526, 48.60109155264209], [-4.091113394547052, 48.60105428748365], [-4.091239677629678, 48.60102117705397], [-4.091304224435874, 48.60101838778776], [-4.091358330983528, 48.60103057321292], [-4.091
435411165457, 48.601068634795006], [-4.091629688202654, 48.60111195154088], [-4.091888268062753, 48.601073947076614], [-4.092150677721312, 48.60101802851011], [-4.09256296335182, 48.60087882745356], [-4.092
763242159161, 48.60101870192594], [-4.093138933976361, 48.60127944051979]], [[-4.091663324570971, 48.60115808901563], [-4.091656765528444, 48.6011543999416], [-4.091793230284388, 48.60125166801022], [-4.091
663324570971, 48.60115808901563]]], '14623476': [[[-4.091752283115965, 48.60257961371299], [-4.092986977723255, 48.60217514212653], [-4.093146765250103, 48.602564234037146], [-4.093174495093603, 48.60274786
146317], [-4.09322570326558, 48.60299517877149], [-4.092849276525119, 48.60292223298955], [-4.092734219518715, 48.602914184795324], [-4.092333080999705, 48.60292390296527], [-4.092205244727745, 48.602924745
99782], [-4.092107008033497, 48.60290219303366], [-4.091977082010071, 48.60280371486902], [-4.091941026748157, 48.602762227793356], [-4.091831063259065, 48.60266584376986], [-4.091752283115965, 48.602579613
71299]]], '14623477': [[[-4.09085453615629, 48.60211780090077], [-4.092260955417791, 48.601614615681385], [-4.092264848736396, 48.60161692321913], [-4.092680241264177, 48.60186326768933], [-4.09275594564794
6, 48.60187884211412], [-4.092755370521903, 48.60187906929406], [-4.092727608487825, 48.60191893852233], [-4.092727520536377, 48.60191906299317], [-4.092788882789239, 48.601956781138824], [-4.09282287533923
7, 48.6019806712296], [-4.092851312422555, 48.602007773348866], [-4.092908449786691, 48.60206776554821], [-4.092937728657649, 48.60209850857611], [-4.092950242591566, 48.60210788002749], [-4.092967226925856
, 48.60212059887198], [-4.09296792232944, 48.60212252079851], [-4.092986643962358, 48.602174323932786], [-4.092986959063142, 48.6021750899548], [-4.092986977723255, 48.60217514212653], [-4.091752283115965, 
48.60257961371299], [-4.0916283609934, 48.60244397026203], [-4.091229339370908, 48.60227246645101], [-4.091040327452925, 48.60219482965371], [-4.09085453615629, 48.60211780090077]]], '14623479': [[[-4.08941
6083442157, 48.60117219697847], [-4.089470495896397, 48.601063342042224], [-4.089514587298626, 48.60100413387407], [-4.089474885392403, 48.60068285199773], [-4.089716524659943, 48.60058612132775], [-4.08971
7059225771, 48.600585907334654], [-4.089764782607749, 48.600597922757885], [-4.089767450648738, 48.60059882872706], [-4.090013893831465, 48.600682511425624], [-4.090003975899834, 48.60074095087379], [-4.090
072855896009, 48.60080638991171], [-4.090171330788049, 48.60083512844979], [-4.09037746990051, 48.60073814858808], [-4.090551323190453, 48.60074529589191], [-4.090713316203616, 48.600782947314244], [-4.0907
86613178065, 48.600744751283386], [-4.090846212233334, 48.60066000171149], [-4.09096545804373, 48.60061356752632], [-4.091171401285553, 48.60061959220807], [-4.091446966219979, 48.600604615329864], [-4.0916
4805027615, 48.60060501823298], [-4.091768347230142, 48.600541148145275], [-4.091939780779361, 48.60057160395646], [-4.092111508788406, 48.6005736294532], [-4.092196691577347, 48.600557631148995], [-4.09226
0147476794, 48.60049113439247], [-4.092366809559683, 48.600455544979376], [-4.092738200077834, 48.60045723119887], [-4.092886413263164, 48.60050362359439], [-4.092884320540728, 48.600700083883545], [-4.0926
28292194498, 48.60079003341756], [-4.092200382612945, 48.600927396217266], [-4.091746421470174, 48.60104921564274], [-4.0915533032217, 48.60103698884982], [-4.091440447844634, 48.60106668661691], [-4.091362
166299986, 48.601027007883076], [-4.091307220416602, 48.60101526997817], [-4.091242553376912, 48.60101779547968], [-4.091104230195084, 48.60105340510322], [-4.090939783911248, 48.60108687080693], [-4.090729
313179146, 48.60114843645745], [-4.090405623511819, 48.60125541791226], [-4.089839629255735, 48.60159202503928], [-4.089652006337438, 48.60154954538038], [-4.089539300274751, 48.6013428149315], [-4.08942319
1546032, 48.60118785687474], [-4.089416083442157, 48.60117219697847]]], '14670247': [[[-4.088558278336071, 48.60363113991667], [-4.088913828981894, 48.60368889635286], [-4.089100256138443, 48.60373511662026
], [-4.089068186395064, 48.60341921497332], [-4.089079706040541, 48.60327072152218], [-4.089182358858672, 48.60329540754456], [-4.089504851875692, 48.603388464001085], [-4.089573780690785, 48.60338525075392
4], [-4.08950902236966, 48.603455023146935], [-4.089426148336481, 48.60372043821832], [-4.089368214580714, 48.603797974756596], [-4.089511446882807, 48.60413455980302], [-4.089475593620373, 48.6041227331533
4], [-4.08923052533345, 48.60404188781784], [-4.089164669690858, 48.604011996477304], [-4.088956522796219, 48.60390145883755], [-4.088647540748028, 48.603765167686305], [-4.088594107964616, 48.60371302132267], [-4.088558278336071, 48.60363113991667]]]}
Is there something wrong?

**Comment by suojifeng** [comment]
> Given your example, " _If I give you the data { "type": "Feature", "properties": { "ID_PARCEL": "2852037", "SURF_PARC": 3.19, "CODE_CULTU": "ORH", "CODE_GROUP": "3", "CULTURE_D1": "DVN", "CULTURE_D2": "DPH" }} ，I would like to know this lab_rpg form of this data_ "
> 
> the lab_rpg form should be {'CODE_GROUP': {'2852037': '3'}}.
> 
> Please note that the input is a featurecollection (in geojson format). The repo already contains an [example](https://github.com/ellaampy/GEE-to-NPY/tree/master/sample_geojson)
I would greatly appreciate it if you had the google drive data 
And I'm wondering if it's a Win11 problem.
i found total ignored parcels 12

**Comment by ellaampy** [comment]
Did you receive any errors? I re-run the script for Sentinel-1 and 2 using the sample geojson provided. In either case, there were no issues.  
![save](https://github.com/ellaampy/GEE-to-NPY/assets/29193227/afc03485-753b-4302-b41a-35810288689c)
